# -*- coding: utf-8 -*-
"""Library Management system .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEJGKW20YYJUSNp8lhEU7asgmu5ee87d

**Importing Modules**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Import CSV file**"""

import pandas as pd
df = pd.read_csv("/content/library managemnt system .csv")

print(df)

"""**Generate five few rows of the Dataset**"""

print(df.head())

"""**Total number of Rows and columns**"""

df.shape

"""**Get the Basic Information about the Dataset**"""

df.info()

"""**Checking Missing Values In the Dataset**"""

df.isnull().sum()

"""**Remove Extra Spaces From Column**"""

df.columns = df.columns.str.strip()

print(df.columns)

"""**Remove Duplicates Rows if any**"""

df = df.drop_duplicates()

print(df.shape)

"""**Check Duplicates Explicitly**"""

df.duplicated().sum()

"""**Display All Available books**"""

available_books = df[df['Status'] == 'Present']
print(available_books)

print(df.columns)

"""**Length of Available Books**"""

len(available_books)

"""**Status of all Books in the Library by Showing Visually**"""

import matplotlib.pyplot as plt
status_counts = df['Status'].value_counts()
status_counts.plot(kind='bar')
plt.title("Status of All Books in Library")
plt.xlabel("Status")
plt.ylabel("Number of Books")
plt.show()

"""**Drawing Histogram**"""

plt.hist(df['Signal_Strength'],bins=10)
plt.title('Signal Strength Distribution')
plt.xlabel("Signal Strength")
plt.ylabel("Number of Books")
plt.show()

"""**Heatmap Representation**"""

import seaborn as sns
sns.heatmap(df.corr(numeric_only=True),annot=True)
plt.show()

"""**Understand Books Availability**"""

print(df['Status'].value_counts())

"""**Save final cleaned dataset**"""

df.to_csv("final_library_data.csv", index=False)

import os
os.listdir('/content')

final_df = pd.read_csv("final_library_data.csv")
final_df.head()

"""**Final Summary Table**"""

Summary = {
  "Total Books": len(df),
  "Available Books":len(final_df[final_df['Status'] == 'Present']),
  "Issued Books": len(final_df[final_df['Status'] != 'Present']),
  "Total Categories":final_df['Category'].nunique(),
  "Total Authors":final_df['Author'].nunique()
}
summary_df = pd.DataFrame(Summary,index=[0])
summary_df