# -*- coding: utf-8 -*-
"""online sales data analysis .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175_6Zpio2a32h6LbLI8UPjke_OqDTL7K

**Importing Libraries**
"""

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

"""**Read CSV File**"""

df=pd.read_csv("/content/online sales data.csv")

print(df)

"""**REMOVE FULLY EMPTY COLUMNS**"""

df.dropna(axis=1, how='all', inplace=True)
print(df)

df.columns

"""**Return First Five Rows of the Dataset**"""

print(df.head())

"""**Number of Rows and Columns**"""

df.shape

"""**Statistical Summary of the Dataset**"""

df.describe()

"""**Names of all the Columns in the Dataset**"""

df.columns

"""**Checking Null values in the Dataset**"""

df.isna().sum()

"""**Concise Summary of the Dataset**"""

df.info()

"""**OPTIMIZED MISSING VALUE HANDLING**"""

df = df.dropna(axis=1, how='all')
print(df)

"""**Impute numeric columns (mean)**"""

num_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[num_cols] = SimpleImputer(strategy='mean').fit_transform(df[num_cols])
print(num_cols)
print(df[num_cols])

"""**Handle missing values in categorical columns**"""

cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

print("Missing Values After Imputation:\n", df.isnull().sum())

"""**Handling Null Values From Numeric Datatype**"""

df.isnull().sum()

"""**Checking Total Missing Values in the Dataset**"""

df.isnull().sum().sum()

"""**Imputation**"""

from sklearn.impute import SimpleImputer
import numpy as np

# 1. Identify numerical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

# 2. Identify numeric columns that actually contain missing values
cols_to_impute = num_cols[df[num_cols].isnull().any()].tolist()

# 3. Create imputer
imputer = SimpleImputer(strategy='mean')

# 4. Apply imputer
for col in cols_to_impute:
    if df[col].isnull().all():
        # Column is completely NaN → mean imputation not possible
        df[col] = df[col].fillna(0)   # OR choose other value
    else:
        df[col] = imputer.fit_transform(df[[col]])

imputer = SimpleImputer(strategy='mean')

df[num_cols] = imputer.fit_transform(df[num_cols])

df = df.dropna(axis=1, how='all')

# Drop fully empty columns
df = df.dropna(axis=1, how='all')

# Identify numeric columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Mean imputation for numeric columns
df[num_cols] = SimpleImputer(strategy='mean').fit_transform(df[num_cols])

from sklearn.impute import SimpleImputer
import numpy as np

# 1. Drop columns that are completely empty (all NaN)
df = df.dropna(axis=1, how='all')

# 2. Identify all numerical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

# 3. Create mean imputer
imputer = SimpleImputer(strategy='mean')

# 4. Apply imputer to numeric columns
df[num_cols] = imputer.fit_transform(df[num_cols])

print("Missing values handled successfully!")
df.head()

df.isna().sum()

df.info()

"""**HANDLING MISSING VALUES FROM OBJECT COLUMN**"""

df.dropna(inplace = True)

df.isna().sum()

df.head()

"""**Data Preprocessing**"""

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y', errors='coerce')

df['Month'] = df['Date'].dt.month_name()
df['Year'] = df['Date'].dt.year

df.sort_values(by='Date', inplace=True)

df.head()

print(df[['Date', 'Month', 'Year']].head())

"""#EDA(EXPLORATORY DATA ANALYSIS)

**1. Which Product Sold the Most Worldwide?**
"""

df.groupby('Product Category')['Total Revenue'].sum().reset_index()

sales_by_category = df.groupby('Product Category')['Total Revenue'].sum().reset_index()

sales_by_category.sort_values(by = 'Total Revenue', ascending = False, inplace = True)

sales_by_category.head()

"""**Total Revenue for each Product Category**"""

px.bar(sales_by_category, x = 'Product Category', y = 'Total Revenue', color = 'Product Category')

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

df['Month'] = df['Date'].dt.month_name()
df['year'] = df['Date'].dt.year

df.sort_values(by='Date',inplace=True)

df['month'] = df['Date'].dt.month_name()
df['year']  = df['Date'].dt.year

df.head()

"""**Monthly Sales Trends**"""

monthly_sales = df.groupby("Month")['Total Revenue'].sum().reset_index()

fig = px.line(
    monthly_sales,
    x="Month",
    y="Total Revenue",
    title="Monthly Sales Trend"
)
fig.show()

"""**Region-wise Revenue**"""

region_sales = df.groupby("Region")['Total Revenue'].sum().reset_index()
fig = px.bar(
    region_sales,
    x="Region",
    y="Total Revenue",
    title="Region-wise Revenue"
)
fig.show()

"""**Top 10 Best-Selling Products**"""

top_products = df.groupby("Product Category")['Total Revenue'].sum().reset_index()
top_products.sort_values(by="Total Revenue", ascending=False, inplace=True)
top_products = top_products.head(10)
fig = px.bar(
    top_products,
    x="Product Category",
    y="Total Revenue",
    title="Top 10 Best-Selling Products"
)
fig.show()

"""**Generate Boxplot For Total Revenue**"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
sns.boxplot(x=df['Total Revenue'])
plt.title("Boxplot of Total Revenue")
plt.show()

"""**Histogram of Total Revenue**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
plt.hist(df['Total Revenue'], bins=30)
plt.title("Histogram of Total Revenue")
plt.xlabel("Total Revenue")
plt.ylabel("Frequency")
plt.show()

"""**Payment Method Analysis using Pie Chart**"""

import plotly.express as px

payment_sales = df.groupby("Payment Method")['Total Revenue'].sum().reset_index()
fig = px.pie(
    payment_sales,
    values="Total Revenue",
    names="Payment Method",
    title="Payment Method Distribution"
)
fig.show()

"""**Heatmap for Missing Values**"""

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Missing Values in the Dataset")
plt.show()

"""**Summary Insights**"""

import pandas as pd
from sklearn.impute import SimpleImputer
import numpy as np

# Re-define df by loading the CSV
df = pd.read_csv("/content/online sales data.csv")

# Drop columns that are completely empty (all NaN)
df = df.dropna(axis=1, how='all')

# Identify numerical columns and apply mean imputation
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
imputer = SimpleImputer(strategy='mean')
df[num_cols] = imputer.fit_transform(df[num_cols])

# Convert 'Date' column to datetime objects
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

# Extract 'Month' and 'year'
df['Month'] = df['Date'].dt.month_name()
df['year'] = df['Date'].dt.year

# Sort DataFrame by 'Date'
df.sort_values(by='Date',inplace=True)

# Original content for generating insights
sales_by_category = df.groupby('Product Category')['Total Revenue'].sum().reset_index()
sales_by_category.sort_values(by = 'Total Revenue', ascending = False, inplace = True)

top_products = df.groupby("Product Category")['Total Revenue'].sum().reset_index()
top_products.sort_values(by="Total Revenue", ascending=False, inplace=True)
top_products = top_products.head(10)

region_sales = df.groupby("Region")['Total Revenue'].sum().reset_index()

payment_sales = df.groupby("Payment Method")['Total Revenue'].sum().reset_index()

print("\n---KEY INSIGHTS---")
print(f"Highest Revenue Generated: {sales_by_category.iloc[0]['Product Category']}")
print(f"Top Selling Product: {top_products.iloc[0]['Product Category']}")
print("Region with Highest Sales:", region_sales.sort_values(by='Total Revenue', ascending=False).iloc[0]['Region'])
print("Best Payment Method:", payment_sales.sort_values(by='Total Revenue', ascending=False).iloc[0]['Payment Method'])